### ISSUE TITLE
Can't create knobs whose arc crosses the 0° point

### ISSUE THREAD

**Issue by modmatrix** [RadMie/ng-knob#12]
I would like to create a knob with a startAngle of about 210, which increases in value clockwise, and has an endAngle of about 150.

In other words, I'm basically trying to create the upside-down version of the "Angles" example on the demo page.

But, no matter what I do, I can't get ng-knob to draw a knob that crosses the 0° mark. Whenever I specify an endAngle that's less than the startAngle, I just get a knob with a narrow wedge that increases in value counterclockwise.

Could this be addressed by adding a spinDirection option, with possible values of "clockwise" and "counterclockwise"?

Or, alternately, with an angleBehavior option, with possible values of "useShortArc" and "useLongArc" (indicating whether to use the shorter of the two possible paths between startAngle and endAngle, or the longer)?

Great plugin, aside from this small detail!

**Comment by camilopalacios** [comment]
You have to set the startAngle to a negative value. Instead of 210 it would be -150 ( = 360 - 210):

that.options = {
        startAngle:-150,
        endAngle:150,
        ...

**Comment by camilopalacios** [comment]
Sorry, I meant 210 - 360, but you get the point.

**Comment by modmatrix** [comment]
Oh, sweet. Thanks!
