### ISSUE TITLE
Responsive Knob - not a issue but question

### ISSUE THREAD

**Issue by flythird** [RadMie/ng-knob#41]
Hello ! 

Thanks for  this very good tool. 
I use it in all my applications.

I plug my own directive knob. To be responsive i use a ratio during the link directive i am able to know the screen size. So i have a false responsive behavior. Just for the initialisation.

My question : is it possible to have a responsive behavior for the size knob object with css ?
i would like this kind of behavior : 

.knob {
 data-width: 50;
 data-height: 50;
}
 ....max-width 480px {
 data-width:35;
 data-height:35;
}

Thanks for your attention, have a nice day.
alien from south of france where the english is not fluent.

**Comment by dceejay** [comment]
Please use the google mailing list for questions that are not issues with the code. Thanks
